/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DatabaseConnection.DatabaseConnection;
import DatabaseConnection.Schedule_TicketDAO;
import font.SetFont;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenlee
 */
public class Schedule extends javax.swing.JFrame {
    private SetFont font;
    private DatabaseConnection databaseconection;
    private Schedule_TicketDAO scheduleDAO;
    

    /**
     * Creates new form showtime
     */
    public Schedule() {
        font = new SetFont();
        scheduleDAO = new Schedule_TicketDAO();
        initComponents();
        
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_insert = new javax.swing.JDialog();
        jPanel51 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        movieID11 = new javax.swing.JLabel();
        movieBox11 = new javax.swing.JComboBox<>();
        roomID11 = new javax.swing.JLabel();
        roomBox11 = new javax.swing.JComboBox<>();
        showtime11 = new javax.swing.JLabel();
        txtshowtime11 = new javax.swing.JTextField();
        date11 = new javax.swing.JLabel();
        price11 = new javax.swing.JLabel();
        priceText11 = new javax.swing.JTextField();
        Jdate = new com.toedter.calendar.JDateChooser();
        ok = new javax.swing.JButton();
        cacel = new javax.swing.JButton();
        txtschedule11 = new javax.swing.JTextField();
        sheduleID11 = new javax.swing.JLabel();
        jDialog_edit = new javax.swing.JDialog();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        movieID12 = new javax.swing.JLabel();
        movieBox12 = new javax.swing.JComboBox<>();
        roomID12 = new javax.swing.JLabel();
        roomBox12 = new javax.swing.JComboBox<>();
        showtime12 = new javax.swing.JLabel();
        txtshowtime12 = new javax.swing.JTextField();
        date12 = new javax.swing.JLabel();
        price12 = new javax.swing.JLabel();
        priceText12 = new javax.swing.JTextField();
        Jdate11 = new com.toedter.calendar.JDateChooser();
        ok12 = new javax.swing.JButton();
        cancel12 = new javax.swing.JButton();
        txtschedule12 = new javax.swing.JTextField();
        sheduleID12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        showtittle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel51.setPreferredSize(new java.awt.Dimension(810, 500));

        jPanel50.setBackground(new java.awt.Color(153, 255, 204));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        movieID11.setText("Movie ID:");
        jPanel48.add(movieID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 102, 45));

        movieBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBox3ActionPerformed(evt);
            }
        });
        jPanel48.add(movieBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 45));

        roomID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomID11.setText("Room ID:");
        jPanel48.add(roomID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 102, 33));

        jPanel48.add(roomBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 200, 44));

        showtime11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showtime11.setText("Show Time:");
        jPanel48.add(showtime11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 102, 33));

        txtshowtime11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel48.add(txtshowtime11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 152, 41));

        date11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date11.setText("Show Date:");
        jPanel48.add(date11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 102, 33));

        price11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price11.setText("Price:");
        jPanel48.add(price11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 76, 32));

        priceText11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel48.add(priceText11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 196, 44));

        Jdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jdate.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 15));
        jPanel48.add(Jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 196, 45));

        ok.setBackground(new java.awt.Color(102, 23, 26));
        ok.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("Ok");
        jPanel48.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 150, 51));

        cacel.setBackground(new java.awt.Color(102, 23, 26));
        cacel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cacel.setForeground(new java.awt.Color(255, 255, 255));
        cacel.setText("Cancel");
        jPanel48.add(cacel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 150, 51));
        jPanel48.add(txtschedule11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 50));

        sheduleID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sheduleID11.setText("ScheduleID:");
        jPanel48.add(sheduleID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel49.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 500));

        jPanel50.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel51Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel51Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jDialog_insertLayout = new javax.swing.GroupLayout(jDialog_insert.getContentPane());
        jDialog_insert.getContentPane().setLayout(jDialog_insertLayout);
        jDialog_insertLayout.setHorizontalGroup(
            jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_insertLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog_insertLayout.setVerticalGroup(
            jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_insertLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel52.setPreferredSize(new java.awt.Dimension(810, 500));

        jPanel53.setBackground(new java.awt.Color(153, 255, 204));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        movieID12.setText("Movie ID:");
        jPanel55.add(movieID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 102, 45));

        movieBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBox12movieBox3ActionPerformed(evt);
            }
        });
        jPanel55.add(movieBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 45));

        roomID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomID12.setText("Room ID:");
        jPanel55.add(roomID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 102, 33));

        jPanel55.add(roomBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 200, 44));

        showtime12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showtime12.setText("Show Time:");
        jPanel55.add(showtime12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 102, 33));

        txtshowtime12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel55.add(txtshowtime12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 152, 41));

        date12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date12.setText("Show Date:");
        jPanel55.add(date12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 102, 33));

        price12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price12.setText("Price:");
        jPanel55.add(price12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 76, 32));

        priceText12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel55.add(priceText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 196, 44));

        Jdate11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jdate.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 15));
        jPanel55.add(Jdate11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 196, 45));

        ok12.setBackground(new java.awt.Color(102, 23, 26));
        ok12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok12.setForeground(new java.awt.Color(255, 255, 255));
        ok12.setText("Ok");
        jPanel55.add(ok12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 150, 51));

        cancel12.setBackground(new java.awt.Color(102, 23, 26));
        cancel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel12.setForeground(new java.awt.Color(255, 255, 255));
        cancel12.setText("Cancel");
        jPanel55.add(cancel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 150, 51));
        jPanel55.add(txtschedule12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 50));

        sheduleID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sheduleID12.setText("ScheduleID:");
        jPanel55.add(sheduleID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 500));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jDialog_editLayout = new javax.swing.GroupLayout(jDialog_edit.getContentPane());
        jDialog_edit.getContentPane().setLayout(jDialog_editLayout);
        jDialog_editLayout.setHorizontalGroup(
            jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_editLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog_editLayout.setVerticalGroup(
            jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_editLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 688));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBackground(new java.awt.Color(195, 170, 170, 123));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setBackground(new java.awt.Color(102, 23, 26));
        insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel3.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 162, 51));

        delete.setBackground(new java.awt.Color(102, 23, 26));
        delete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 165, 51));

        edit.setBackground(new java.awt.Color(102, 23, 26));
        edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 163, 51));

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBackground(new java.awt.Color(226, 226, 229));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Movie ID", "Room ID", "Show time ", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setBounds(new java.awt.Rectangle(20, 40, 1150, 260));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 460));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1200, 580));

        showtittle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        font.setFontRobotoBold(showtittle, 24f);
        showtittle.setText("Schedule");
        jPanel4.add(showtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1280, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cinéverse (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        jPanel1.add(jPanel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
       /*
        try{
            Connection con = databaseconection.getConnection();
            
            
        }catch(Exception e){
            
        }
        // TODO add your handling code here:
        ArrayList<String> list1 =  Util.loaddatacomboboxMovie();
         
        for(String item: list1){
            movieBox.addItem(item);
             
        }
        
        
        ArrayList<String> list2 =  Util.loaddatacomboboxRoom();
         
        for(String item: list2){
            roomBox.addItem(item);
             
        }
        */
        
       
        
        
    }//GEN-LAST:event_insertActionPerformed

    private void movieBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieBox3ActionPerformed

    private void movieBox12movieBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieBox12movieBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieBox12movieBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdate;
    private com.toedter.calendar.JDateChooser Jdate11;
    private javax.swing.JButton cacel;
    private javax.swing.JButton cancel12;
    private javax.swing.JLabel date11;
    private javax.swing.JLabel date12;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton insert;
    private javax.swing.JDialog jDialog_edit;
    private javax.swing.JDialog jDialog_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> movieBox11;
    private javax.swing.JComboBox<String> movieBox12;
    private javax.swing.JLabel movieID11;
    private javax.swing.JLabel movieID12;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok12;
    private javax.swing.JLabel price11;
    private javax.swing.JLabel price12;
    private javax.swing.JTextField priceText11;
    private javax.swing.JTextField priceText12;
    private javax.swing.JComboBox<String> roomBox11;
    private javax.swing.JComboBox<String> roomBox12;
    private javax.swing.JLabel roomID11;
    private javax.swing.JLabel roomID12;
    private javax.swing.JLabel sheduleID11;
    private javax.swing.JLabel sheduleID12;
    private javax.swing.JLabel showtime11;
    private javax.swing.JLabel showtime12;
    private javax.swing.JLabel showtittle;
    private javax.swing.JTextField txtschedule11;
    private javax.swing.JTextField txtschedule12;
    private javax.swing.JTextField txtshowtime11;
    private javax.swing.JTextField txtshowtime12;
    // End of variables declaration//GEN-END:variables


public void setData() {
    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    tableModel.setRowCount(0); // Xóa tất cả các hàng trong bảng

    for (model.Schedule_model s : scheduleDAO.getSchedules()) {
        String[] rowData = {
            s.getScid(),
            s.getMid(),
            s.getRid(),
            s.getSdate().toString(), // Chuyển LocalDate sang String
            s.getStime().toString(), // Chuyển LocalTime sang String
            String.valueOf(s.getPrice())
        };
        tableModel.addRow(rowData); // Thêm dòng vào bảng
    }
}
public void setActionListener(ActionListener ac){
        insert.addActionListener(ac);
        edit.addActionListener(ac);
        delete.addActionListener(ac);
        
        
    }


public void refreshMovieInfor(){
     
}
     
     
     
     
     
     
     

}
