/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DatabaseConnection.DatabaseConnection;
import DatabaseConnection.Schedule_TicketDAO;
import controller.Schedulecontroller;
import font.SetFont;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Schedule_model;

/**
 *
 * @author kenlee
 */
public class Schedulepanel extends javax.swing.JPanel {
    private SetFont font;
    private Schedule_TicketDAO scheduleDAO;
    private DatabaseConnection databaseconection;
    

    public Schedulepanel() {
        font = new  SetFont();
        scheduleDAO = new Schedule_TicketDAO();
        databaseconection = new DatabaseConnection();
        initComponents();
        setData();
        Schedulecontroller schedulecontroller = new Schedulecontroller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_insert = new javax.swing.JDialog();
        jPanel51 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        movieID11 = new javax.swing.JLabel();
        cb_movie1 = new javax.swing.JComboBox<>();
        roomID11 = new javax.swing.JLabel();
        cb_room1 = new javax.swing.JComboBox<>();
        showtime11 = new javax.swing.JLabel();
        tf_time1 = new javax.swing.JTextField();
        date11 = new javax.swing.JLabel();
        price11 = new javax.swing.JLabel();
        tf_price1 = new javax.swing.JTextField();
        Jdate1 = new com.toedter.calendar.JDateChooser();
        ok_insert = new javax.swing.JButton();
        cancel_insert = new javax.swing.JButton();
        tf_schedule1 = new javax.swing.JTextField();
        sheduleID11 = new javax.swing.JLabel();
        jDialog_edit = new javax.swing.JDialog();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        movieID12 = new javax.swing.JLabel();
        cb_movie2 = new javax.swing.JComboBox<>();
        roomID12 = new javax.swing.JLabel();
        cb_room2 = new javax.swing.JComboBox<>();
        showtime12 = new javax.swing.JLabel();
        tf_time2 = new javax.swing.JTextField();
        date12 = new javax.swing.JLabel();
        price12 = new javax.swing.JLabel();
        tf_price2 = new javax.swing.JTextField();
        Jdate2 = new com.toedter.calendar.JDateChooser();
        ok_edit = new javax.swing.JButton();
        cancel_edit = new javax.swing.JButton();
        tf_schedule2 = new javax.swing.JTextField();
        sheduleID12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTschedule = new javax.swing.JTable();
        showtittle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jDialog_insert.setSize(new java.awt.Dimension(820, 540));

        jPanel51.setPreferredSize(new java.awt.Dimension(810, 500));

        jPanel50.setBackground(new java.awt.Color(153, 255, 204));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        movieID11.setText("Movie ID:");
        jPanel48.add(movieID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 102, 45));

        cb_movie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_movie1movieBox3ActionPerformed(evt);
            }
        });
        jPanel48.add(cb_movie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 45));

        roomID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomID11.setText("Room ID:");
        jPanel48.add(roomID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 102, 33));

        jPanel48.add(cb_room1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 200, 44));

        showtime11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showtime11.setText("Show Time:");
        jPanel48.add(showtime11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 102, 33));

        tf_time1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel48.add(tf_time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 152, 41));

        date11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date11.setText("Show Date:");
        jPanel48.add(date11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 102, 33));

        price11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price11.setText("Price:");
        jPanel48.add(price11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 76, 32));

        tf_price1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel48.add(tf_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 196, 44));

        Jdate1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jdate2.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 15));
        jPanel48.add(Jdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 196, 45));

        ok_insert.setBackground(new java.awt.Color(102, 23, 26));
        ok_insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok_insert.setForeground(new java.awt.Color(255, 255, 255));
        ok_insert.setText("OK");
        ok_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_insertActionPerformed(evt);
            }
        });
        jPanel48.add(ok_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 150, 51));

        cancel_insert.setBackground(new java.awt.Color(102, 23, 26));
        cancel_insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel_insert.setForeground(new java.awt.Color(255, 255, 255));
        cancel_insert.setText("Cancel");
        jPanel48.add(cancel_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 150, 51));
        jPanel48.add(tf_schedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 50));

        sheduleID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sheduleID11.setText("ScheduleID:");
        jPanel48.add(sheduleID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel49.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 500));

        jPanel50.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel51Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel51Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jDialog_insertLayout = new javax.swing.GroupLayout(jDialog_insert.getContentPane());
        jDialog_insert.getContentPane().setLayout(jDialog_insertLayout);
        jDialog_insertLayout.setHorizontalGroup(
            jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_insertLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog_insertLayout.setVerticalGroup(
            jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jDialog_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_insertLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jDialog_edit.setSize(new java.awt.Dimension(810, 540));

        jPanel52.setPreferredSize(new java.awt.Dimension(810, 500));

        jPanel53.setBackground(new java.awt.Color(153, 255, 204));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel55.setSize(new java.awt.Dimension(810, 540));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        movieID12.setText("Movie ID:");
        jPanel55.add(movieID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 102, 45));

        cb_movie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_movie2movieBox3ActionPerformed(evt);
            }
        });
        jPanel55.add(cb_movie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 50));

        roomID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomID12.setText("Room ID:");
        jPanel55.add(roomID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 102, 33));

        jPanel55.add(cb_room2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 200, 44));

        showtime12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showtime12.setText("Show Time:");
        jPanel55.add(showtime12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 102, 33));

        tf_time2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel55.add(tf_time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 190, 50));

        date12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date12.setText("Show Date:");
        jPanel55.add(date12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 102, 33));

        price12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price12.setText("Price:");
        jPanel55.add(price12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 76, 32));

        tf_price2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel55.add(tf_price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 196, 44));

        Jdate2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jdate2.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 15));
        jPanel55.add(Jdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 196, 45));

        ok_edit.setBackground(new java.awt.Color(102, 23, 26));
        ok_edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok_edit.setForeground(new java.awt.Color(255, 255, 255));
        ok_edit.setText("OK");
        jPanel55.add(ok_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 150, 51));

        cancel_edit.setBackground(new java.awt.Color(102, 23, 26));
        cancel_edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel_edit.setForeground(new java.awt.Color(255, 255, 255));
        cancel_edit.setText("Cancel");
        jPanel55.add(cancel_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 150, 51));
        jPanel55.add(tf_schedule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 50));

        sheduleID12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sheduleID12.setText("ScheduleID:");
        jPanel55.add(sheduleID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 500));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jDialog_editLayout = new javax.swing.GroupLayout(jDialog_edit.getContentPane());
        jDialog_edit.getContentPane().setLayout(jDialog_editLayout);
        jDialog_editLayout.setHorizontalGroup(
            jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_editLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog_editLayout.setVerticalGroup(
            jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jDialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog_editLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setPreferredSize(new java.awt.Dimension(1366, 688));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 688));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBackground(new java.awt.Color(195, 170, 170, 123));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 ,100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setBackground(new java.awt.Color(102, 23, 26));
        insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Insert");
        jPanel3.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 162, 51));

        delete.setBackground(new java.awt.Color(102, 23, 26));
        delete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 165, 51));

        edit.setBackground(new java.awt.Color(102, 23, 26));
        edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 163, 51));

        jScrollPane1.setBorder(null);

        jTschedule.setBackground(new java.awt.Color(204, 204, 204));
        jTschedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Movie ID", "Room ID", "Show date ", "Show time", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTschedule.setBounds(new java.awt.Rectangle(20, 40, 1150, 260));
        jScrollPane1.setViewportView(jTschedule);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 460));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1200, 580));

        showtittle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        showtittle.setText("Schedule");
        jPanel4.add(showtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1280, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cinéverse (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_movie1movieBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_movie1movieBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_movie1movieBox3ActionPerformed

    private void cb_movie2movieBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_movie2movieBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_movie2movieBox3ActionPerformed

    private void ok_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_insertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ok_insertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdate1;
    private com.toedter.calendar.JDateChooser Jdate2;
    private javax.swing.JButton cancel_edit;
    private javax.swing.JButton cancel_insert;
    private javax.swing.JComboBox<String> cb_movie1;
    private javax.swing.JComboBox<String> cb_movie2;
    private javax.swing.JComboBox<String> cb_room1;
    private javax.swing.JComboBox<String> cb_room2;
    private javax.swing.JLabel date11;
    private javax.swing.JLabel date12;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton insert;
    private javax.swing.JDialog jDialog_edit;
    private javax.swing.JDialog jDialog_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTschedule;
    private javax.swing.JLabel movieID11;
    private javax.swing.JLabel movieID12;
    private javax.swing.JButton ok_edit;
    private javax.swing.JButton ok_insert;
    private javax.swing.JLabel price11;
    private javax.swing.JLabel price12;
    private javax.swing.JLabel roomID11;
    private javax.swing.JLabel roomID12;
    private javax.swing.JLabel sheduleID11;
    private javax.swing.JLabel sheduleID12;
    private javax.swing.JLabel showtime11;
    private javax.swing.JLabel showtime12;
    private javax.swing.JLabel showtittle;
    private javax.swing.JTextField tf_price1;
    private javax.swing.JTextField tf_price2;
    private javax.swing.JTextField tf_schedule1;
    private javax.swing.JTextField tf_schedule2;
    private javax.swing.JTextField tf_time1;
    private javax.swing.JTextField tf_time2;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener ac) {
        insert.addActionListener(ac);
        edit.addActionListener(ac);
        delete.addActionListener(ac);
        ok_insert.addActionListener(ac);
        cancel_insert.addActionListener(ac);
        ok_edit.addActionListener(ac);
        cancel_edit.addActionListener(ac);
    }

    public JButton getEdit() {
        return edit;
    }

    public void setEdit(JButton edit) {
        this.edit = edit;
    }

    public JButton getInsert() {
        return insert;
    }

    public void setInsert(JButton insert) {
        this.insert = insert;
    }

    public JButton getOk_edit() {
        return ok_edit;
    }

    public void setOk_edit(JButton ok_edit) {
        this.ok_edit = ok_edit;
    }

    public JButton getOk_insert() {
        return ok_insert;
    }

    public void setOk_insert(JButton ok_insert) {
        this.ok_insert = ok_insert;
    }

    public JButton getCancel_edit() {
        return cancel_edit;
    }

    public void setCancel_edit(JButton cancel_edit) {
        this.cancel_edit = cancel_edit;
    }

    public JButton getCancel_insert() {
        return cancel_insert;
    }

    public void setCancel_insert(JButton cancel_insert) {
        this.cancel_insert = cancel_insert;
    }


public void setData() {
    DefaultTableModel tableModel = (DefaultTableModel) jTschedule.getModel();
    tableModel.setRowCount(0);

    
    for (model.Schedule_model s : scheduleDAO.getSchedules()) {
       
        String sdateString = s.getSdate().toString(); 
        LocalTime stime = s.getStime(); 

        
        stime = stime.minusHours(1);  

        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String stimeString = stime.format(formatter);  

        
        String[] rowData = {
            s.getScid(),                   
            s.getMid(),                  
            s.getRid(),                    
            sdateString,                 
            stimeString,                   
            String.valueOf(s.getPrice())   
        };
        
        
        tableModel.addRow(rowData);
    }
}


    public void showInsertdialog() {
        
        tf_schedule1.setText(""); 
        cb_movie1.removeAllItems(); 
        cb_room1.removeAllItems();
        Jdate1.setDate(null); 
        tf_time1.setText("");
        tf_price1.setText(""); 
        

         ArrayList<String> list = scheduleDAO.loaddatacomboboxMovie();
         for (String item : list) {
             cb_movie1.addItem(item);  
         }

         
         ArrayList<String> list1 = scheduleDAO.loaddatacomboboxroom();
         for (String item : list1) {
             cb_room1.addItem(item);  
         }

       
        jDialog_insert.setVisible(true);
        
        
        
        }
    

    
    public void showEditDialog() {
    Schedule_model schedule = getSelectedRow();
    
    if (schedule == null) { // Kiểm tra nếu không có dòng nào được chọn
        JOptionPane.showMessageDialog(null, "Please select a showtime to edit.");
        return;
    }
    
    cb_movie2.removeAllItems();
    cb_room2.removeAllItems();

    
    ArrayList<String> list = scheduleDAO.loaddatacomboboxMovie();
    for (String item : list) {
        cb_movie2.addItem(item);  
    }

    ArrayList<String> list1 = scheduleDAO.loaddatacomboboxroom();
    for (String item : list1) {
        cb_room2.addItem(item);  
    }

    
    
    
    
    LocalDate localDate = schedule.getSdate();
    Date date = (localDate != null) ? Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant()) : null;
    
   
    tf_schedule2.setText(schedule.getScid());
    cb_movie2.setSelectedItem(schedule.getMid());
    cb_room2.setSelectedItem(schedule.getRid());
    Jdate2.setDate(date);
    tf_time2.setText(schedule.getStime() != null ? schedule.getStime().toString() : "");
    tf_price2.setText(String.valueOf(schedule.getPrice()));
    
    jDialog_edit.setVisible(true);
}


    public void deleteSchedule() {
        Schedule_model sc = getSelectedRow();
        if(scheduleDAO.isExistschedule(sc.getScid())){
            scheduleDAO.deleteschedule(sc);
            
            setData();
        }else{
            JOptionPane.showMessageDialog(jLabel1,"Schedule is not exited",  "Error Movie ID", JOptionPane.ERROR_MESSAGE);
        }
            

        }

     

    
    private Schedule_model getSelectedRow() {
    DefaultTableModel model = (DefaultTableModel) jTschedule.getModel();
    int selectedRow = jTschedule.getSelectedRow();
    
    if (selectedRow == -1) { 
        return null; 
    }
    
    String scheduleID = model.getValueAt(selectedRow, 0).toString();
    String movieID = model.getValueAt(selectedRow, 1).toString();
    String roomID = model.getValueAt(selectedRow, 2).toString();
    LocalDate sdate = LocalDate.parse(model.getValueAt(selectedRow, 3).toString());
    LocalTime stime = LocalTime.parse(model.getValueAt(selectedRow, 4).toString());
    float price = Float.parseFloat(model.getValueAt(selectedRow, 5).toString());
    
    return new Schedule_model(scheduleID, movieID, roomID, sdate, stime, price);
}
    
    
    public void cancelInsert() {
        int confirm = JOptionPane.showConfirmDialog(jPanel51, "Do you want to cancel?", "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
            // thêm hàm xoá dữ liệu cũ , 
            jPanel51.setVisible(false);
        }
    }
    
     public void cancelEdit() {
        int confirm = JOptionPane.showConfirmDialog(jPanel52, "Do you want to cancel?", "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
            jPanel52.setVisible(false);
        }
    }
     
     
  public void insertSchedule() {
   
    String scid = tf_schedule1.getText();
    String mid = cb_movie1.getSelectedItem().toString();
    String rid = cb_room1.getSelectedItem().toString();
    
    
    LocalDate sdate = Jdate1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalTime stime = LocalTime.parse(tf_time1.getText()); 
     
    stime = stime.plusHours(1); 
    float price = Float.valueOf(tf_price1.getText()); 

    
    Schedule_model s = new Schedule_model();
    s.setScid(scid);
    s.setMid(mid);
    s.setRid(rid);
    s.setSdate(sdate);
    s.setStime(stime);
    s.setPrice(price);

    
    if (scheduleDAO.isExistschedule(s.getScid())) {
        JOptionPane.showMessageDialog(jDialog_insert, "Schedule ID is already existed. Please enter again!", "Insert Schedule Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    scheduleDAO.addSchedule(s);

     setData();
  
    JOptionPane.showMessageDialog(jDialog_insert, "Schedule has been added!", "Adding Successfully", JOptionPane.PLAIN_MESSAGE);
   
    jDialog_insert.setVisible(false);
}


public void editSchedule() {
    
    String scid = tf_schedule2.getText();
    String mid = cb_movie2.getSelectedItem().toString();
    String rid = cb_room2.getSelectedItem().toString();

    
    LocalDate sdate = Jdate2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalTime stime = LocalTime.parse(tf_time2.getText());  

    
    stime = stime.plusHours(1);  // Cộng thêm 1 giờ

    float price = Float.valueOf(tf_price2.getText());

    Schedule_model s = new Schedule_model();
    s.setScid(scid);
    s.setMid(mid);
    s.setRid(rid);
    s.setSdate(sdate);
    s.setStime(stime);  
    s.setPrice(price);

        if (!scheduleDAO.isExistschedule(s.getScid())) {
        JOptionPane.showMessageDialog(jDialog_edit, "Schedule ID does not exist. Please enter again!", "Edit Schedule Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

 
    scheduleDAO.editSchedule(s);
    setData(); 
    JOptionPane.showMessageDialog(jDialog_edit, "Schedule has been edited!", "Editing Successfully", JOptionPane.PLAIN_MESSAGE);
    jDialog_edit.setVisible(false);
}




}
