/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import font.SetFont;

/**
 *
 * @author kenlee
 */
public class Ticket extends javax.swing.JFrame {
    private SetFont font;
    
    
    

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        font = new SetFont();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ticketID = new javax.swing.JLabel();
        ticketID1 = new javax.swing.JLabel();
        tickeType = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        ticketbox = new javax.swing.JComboBox<>();
        showbox = new javax.swing.JComboBox<>();
        txt_time = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        seattype = new javax.swing.JLabel();
        cus_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        seat_box = new javax.swing.JComboBox<>();
        paymethod = new javax.swing.JLabel();
        pay_box = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        insert3 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        ticket = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 688));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(195, 170, 170));
        jPanel4.setBackground(new java.awt.Color(195, 170, 170 , 123));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBackground(new java.awt.Color(255, 255, 255 , 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 688));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticketID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(ticketID, 20f);
        ticketID.setText("Movie Name:");
        jPanel3.add(ticketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 45));

        ticketID1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(ticketID1, 20f);
        ticketID1.setText("Room Type:");
        jPanel3.add(ticketID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 45));

        tickeType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(tickeType, 20f);
        tickeType.setText("Time:");
        jPanel3.add(tickeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 45));

        insert.setBackground(new java.awt.Color(153, 0, 51));
        insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Confirm");
        font.setFontRoboto(insert, 20f);
        jPanel3.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 490, 110, 43));

        cancel.setBackground(new java.awt.Color(153, 0, 51));
        cancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        font.setFontRoboto(cancel, 20f);
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 98, 43));

        ticketbox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(ticketbox, 20f);
        ticketbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel3.add(ticketbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 390, 40));

        showbox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(showbox, 20f);
        jPanel3.add(showbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 391, 40));

        font.setFontRoboto(txt_time, 20f);
        jPanel3.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 40));

        phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(phone, 20f);
        phone.setText("Customer Phone:");
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 154, 45));

        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        font.setFontRoboto(txt_phone, 20f);
        jPanel3.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 228, 45));

        seattype.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(seattype, 20f);
        seattype.setText("Seat number:");
        jPanel3.add(seattype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 115, 45));

        cus_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cus_name.setText("Customer Name:");
        font.setFontRoboto(cus_name, 20f);
        jPanel3.add(cus_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 154, 45));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        font.setFontRoboto(txt_name, 20f);
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 228, 45));

        seat_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(seat_box, 20f);
        jPanel3.add(seat_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, 40));

        paymethod.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        paymethod.setText("Pay method:");
        font.setFontRoboto(paymethod, 20f);
        jPanel3.add(paymethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        pay_box.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        font.setFontRoboto(pay_box, 20f);
        pay_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By cash", "By credit" }));
        pay_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_boxActionPerformed(evt);
            }
        });
        jPanel3.add(pay_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 270, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 690, 550));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setBackground(new java.awt.Color(51, 102, 255,123));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("BILL ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 0, 89, 39));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("hiện tên phim ở đây !");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 6, -1, 29));

        jLabel3.setText("hiện ngày tháng năm");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 41, -1, 23));

        jLabel4.setText("hiện giờ chiếu ở đây / thời lượng bộ phim");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 78, 271, -1));

        jLabel5.setText("Ghế được chọn ở bên kia");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, 30));

        jLabel6.setText("phòng chiếu ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 160));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 220, 320, 70));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Tổng tiền dựa trên số ghế đã chọn");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 215, 57));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, 90));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBackground(new java.awt.Color(255, 255, 255 , 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert3.setBackground(new java.awt.Color(153, 0, 51));
        insert3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insert3.setForeground(new java.awt.Color(255, 255, 255));
        insert3.setText("Pay");
        jPanel9.add(insert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 90, 40));

        cancel1.setBackground(new java.awt.Color(153, 0, 51));
        cancel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel1.setForeground(new java.awt.Color(255, 255, 255));
        cancel1.setText("Cancel");
        jPanel9.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 9, 90, 40));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 210, 60));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 400, 550));

        ticket.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        ticket.setText("Ticket");
        jPanel4.add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 6, 210, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 58, 1210, 620));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cinéverse (2).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void pay_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JLabel cus_name;
    private javax.swing.JButton insert;
    private javax.swing.JButton insert3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> pay_box;
    private javax.swing.JLabel paymethod;
    private javax.swing.JLabel phone;
    private javax.swing.JComboBox<String> seat_box;
    private javax.swing.JLabel seattype;
    private javax.swing.JComboBox<String> showbox;
    private javax.swing.JLabel tickeType;
    private javax.swing.JLabel ticket;
    private javax.swing.JLabel ticketID;
    private javax.swing.JLabel ticketID1;
    private javax.swing.JComboBox<String> ticketbox;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}